name: pingme
description: "PingMe Chat Application"
publish_to: "none"

version: 1.0.0+1

environment:
   sdk: ^3.6.0

dependencies:
   flutter:
      sdk: flutter

   cupertino_icons: ^1.0.8
   flutter_dotenv: ^5.2.1
   dio: ^5.7.0
   fluttertoast: ^8.2.10
   logger: ^2.5.0
   http: ^1.2.2
   flutter_secure_storage: ^9.2.2
   socket_io_client: ^3.0.2
   web_socket_channel: ^3.0.1
   provider: ^6.1.2
   intl: ^0.20.1
   jwt_decoder: ^2.0.1
   flutter_svg: ^2.0.16

dev_dependencies:
   flutter_test:
      sdk: flutter

   flutter_lints: ^5.0.0

flutter:
   uses-material-design: true
   assets:
      - .env
      - .env.development
